name: Update Playlist

on:
  workflow_dispatch:  # Позволяет запускать workflow вручную
  schedule:
    - cron: "0 */6 * * *"  # Запуск каждые 6 часов (в 00:00, 06:00, 12:00, 18:00 UTC)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Указываем версию Python

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Шаг 4: Запускаем скрипт для обновления плейлиста
      - name: Run update script
        run: |
          python update_playlist.py

      # Шаг 5: Коммитим изменения в репозиторий
      - name: Commit updated playlist
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Добавляем файл mpll.m3u в индекс
          git add mpll.m3u
          
          # Проверяем, есть ли изменения для коммита
          if git diff-index --quiet HEAD --
          then
            echo "No changes to commit"
          else
            git commit -m "Auto-update playlist"
            git push
          fi
