name: Update Playlist

on:
  schedule:
    # Запуск в 10:00 и 15:00 UTC
    - cron: "0 10,15 * * *"
  workflow_dispatch: # Добавляем возможность ручного запуска

jobs:
  update_playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run update script
        run: |
          python update_playlist.py

      - name: Commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

          # Проверяем, есть ли изменения в файле mpll.m3u
          if git diff --quiet mpll.m3u; then
            echo "No changes to commit."
          else
            git add mpll.m3u
            git commit -m "Update playlist"
            git push origin main
          fi
