name: Update Playlist

# Триггеры для запуска workflow
on:
  workflow_dispatch:  # Позволяет запускать workflow вручную
  schedule:
    - cron: "0 0 * * *"  # Запуск каждый день в полночь (UTC)

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонируем репозиторий
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Указываем версию Python

      # Шаг 3: Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Шаг 4: Запускаем скрипт для обновления плейлиста
      - name: Run update script
        run: |
          python update_playlist.py

      # Шаг 5: Коммитим изменения в репозиторий
      - name: Commit updated playlist
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Проверяем, есть ли изменения
          git add updated_playlist.m3u
          git diff --quiet || git commit -m "Auto-update playlist" || echo "No changes to commit"
          git push
